name: armTemplateDeployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group with AZ CLI
        uses: Azure/cli@v1
        with: 
          inlinescript: |
            az deployment sub create --location "West Europe" --template-file ./arm-templates/resourcegroup.json
